#!/usr/bin/env python3
"""Render README skill and plugin directory blocks."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MARKETPLACE_PATH = ROOT / ".agents" / "plugins" / "marketplace.json"
README_CONFIGS = (
    {
        "path": ROOT / "README.md",
        "skills_header": ("Skill", "Description"),
        "plugins_header": ("Plugin", "Category", "Version", "Description"),
    },
    {
        "path": ROOT / "README.zh-CN.md",
        "skills_header": ("Skill", "描述"),
        "plugins_header": ("插件", "分类", "版本", "描述"),
    },
)


class RenderError(Exception):
    """Raised when README directory rendering cannot proceed."""


def load_json(path: Path) -> dict:
    try:
        with path.open(encoding="utf-8") as handle:
            return json.load(handle)
    except FileNotFoundError as exc:
        raise RenderError(f"Missing JSON file: {path.relative_to(ROOT)}") from exc
    except json.JSONDecodeError as exc:
        raise RenderError(f"Invalid JSON in {path.relative_to(ROOT)}: {exc}") from exc


def markdown_cell(value: object) -> str:
    text = "" if value is None else str(value)
    text = " ".join(text.split())
    return text.replace("|", "\\|")


def first_sentence(text: str) -> str:
    chinese_stop = text.find("。")
    if chinese_stop != -1:
        return text[: chinese_stop + 1].strip()
    match = re.search(r"(?<=[。.!?])\s", text)
    if match:
        return text[: match.start() + 1].strip()
    return text.strip()


def parse_skill_front_matter(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise RenderError(f"Missing front matter in {path.relative_to(ROOT)}")

    end = text.find("\n---", 4)
    if end == -1:
        raise RenderError(f"Unclosed front matter in {path.relative_to(ROOT)}")

    values: dict[str, str] = {}
    for raw_line in text[4:end].splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue
        if ":" not in raw_line:
            continue
        key, raw_value = raw_line.split(":", 1)
        value = raw_value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        values[key.strip()] = value

    name = values.get("name") or path.parent.name
    description = values.get("description")
    if not description:
        raise RenderError(f"Missing description in {path.relative_to(ROOT)}")
    return name, first_sentence(description)


def render_skills(headers: tuple[str, str]) -> str:
    rows = [
        "<!-- generated by scripts/render-plugin-directory.py; do not edit manually -->",
        "",
        f"| {headers[0]} | {headers[1]} |",
        "|---|---|",
    ]

    for skill_path in sorted((ROOT / "skills").glob("*/SKILL.md")):
        name, description = parse_skill_front_matter(skill_path)
        link = f"./{skill_path.relative_to(ROOT).as_posix()}"
        rows.append(
            f"| [{markdown_cell(name)}]({link}) | {markdown_cell(description)} |"
        )

    return "\n".join(rows)


def plugin_description(plugin_manifest: dict) -> str:
    interface = plugin_manifest.get("interface")
    if isinstance(interface, dict) and interface.get("shortDescription"):
        return str(interface["shortDescription"])
    return str(plugin_manifest.get("description") or "")


def plugin_link(plugin_dir: Path) -> str:
    readme = plugin_dir / "README.md"
    target = readme if readme.exists() else plugin_dir
    return f"./{target.relative_to(ROOT).as_posix()}"


def render_plugins(headers: tuple[str, str, str, str]) -> str:
    marketplace = load_json(MARKETPLACE_PATH)
    plugins = marketplace.get("plugins")
    if not isinstance(plugins, list):
        raise RenderError("marketplace.json must contain a plugins list")

    rows = [
        "<!-- generated by scripts/render-plugin-directory.py; do not edit manually -->",
        "",
        f"| {headers[0]} | {headers[1]} | {headers[2]} | {headers[3]} |",
        "|---|---|---:|---|",
    ]

    for entry in plugins:
        if not isinstance(entry, dict):
            raise RenderError("Each marketplace plugin entry must be an object")
        source = entry.get("source")
        if not isinstance(source, dict) or not source.get("path"):
            name = entry.get("name", "<unknown>")
            raise RenderError(f"Plugin {name} is missing source.path")

        plugin_dir = (ROOT / source["path"]).resolve()
        try:
            plugin_dir.relative_to(ROOT)
        except ValueError as exc:
            raise RenderError(f"Plugin path escapes repository: {source['path']}") from exc

        manifest_path = plugin_dir / ".codex-plugin" / "plugin.json"
        manifest = load_json(manifest_path)
        name = entry.get("name") or manifest.get("name")
        if not name:
            raise RenderError(f"Missing plugin name for {source['path']}")

        rows.append(
            "| "
            + " | ".join(
                [
                    f"[{markdown_cell(name)}]({plugin_link(plugin_dir)})",
                    markdown_cell(entry.get("category") or ""),
                    markdown_cell(manifest.get("version") or ""),
                    markdown_cell(plugin_description(manifest)),
                ]
            )
            + " |"
        )

    return "\n".join(rows)


def replace_block(text: str, block_name: str, rendered: str) -> str:
    start = f"<!-- {block_name}_START -->"
    end = f"<!-- {block_name}_END -->"
    pattern = re.compile(
        rf"{re.escape(start)}\n.*?\n{re.escape(end)}",
        flags=re.DOTALL,
    )
    replacement = f"{start}\n{rendered}\n{end}"
    updated, count = pattern.subn(replacement, text)
    if count != 1:
        raise RenderError(f"Expected exactly one {block_name} block")
    return updated


def render_readme(config: dict[str, object]) -> str:
    path = config["path"]
    assert isinstance(path, Path)
    text = path.read_text(encoding="utf-8")
    text = replace_block(text, "SKILLS", render_skills(config["skills_header"]))
    text = replace_block(text, "PLUGINS", render_plugins(config["plugins_header"]))
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if README directory blocks are stale",
    )
    args = parser.parse_args()

    try:
        changed: list[Path] = []
        for config in README_CONFIGS:
            path = config["path"]
            assert isinstance(path, Path)
            rendered = render_readme(config)
            current = path.read_text(encoding="utf-8")
            if rendered != current:
                changed.append(path)
                if not args.check:
                    path.write_text(rendered, encoding="utf-8")

        if args.check and changed:
            rel_paths = ", ".join(path.relative_to(ROOT).as_posix() for path in changed)
            print(
                "README directory blocks are stale. Run "
                "python3 scripts/render-plugin-directory.py. "
                f"Stale files: {rel_paths}",
                file=sys.stderr,
            )
            return 1
    except RenderError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
